version: "3.4"
services:
  localstack:
    container_name: localstack-test
    image: localstack/localstack:latest
    ports: 
      - 4566:4566
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

networks: 
  default:
    name: localstack
